### ISSUE TITLE
lcf2xml: use own extension when saving XML

### ISSUE THREAD

**Issue by fdelapena** [EasyRPG/Tools#37]
Because converting RPG_RT.lmt -> RPG_RT.xml and RPG_RT.ldb -> RPG_RT.xml use the same destination filename, maybe makes sense saving them as ~RPG_RT.lmt.xml~ RPG_RT.emt and ~RPG_RT.ldb.xml~ RPG_RT.edb. In order to follow the same style, maybe is worth to do the same with ~SaveXX.lsd.xml and MapXXXX.lmu.xml~ SaveXX.esd and MapXXXX.emu even when it is not really needed here. The application code for default input/output filename would be simpler, having the previous extension beforehand.

**Comment by carstene1ns** [comment]
We could even do it the Office way, using e.g. `.lmux` (Microsoft pls.).

**Comment by carstene1ns** [comment]
Outdated, but relevant patch: https://github.com/EasyRPG/Tools/commit/ae6a4fb13a805c736035ecc401422cc140142cda
