### ISSUE TITLE
Gencache: Translated asset directories are ignored

### ISSUE THREAD

**Issue by Flashfyre** [EasyRPG/Tools#65]
There is support for translated assets by putting mirrored asset folders in Language/LANGUAGE_NAME/, for example 'Picture'. Gencache does not pick up these directories. When index.json is edited manually to include them, translated assets work as intended.

**Comment by Ghabry** [comment]
It is possible that you hit the recursion limit.

Try ``gencache -r 4``

**Comment by Flashfyre** [comment]
This has fixed the problem. Thank you.
