### ISSUE TITLE
not well-formed (invalid token)

### ISSUE THREAD

**Issue by nippanippa** [EasyRPG/Tools#66]
I'm having a serious problem I've never had to deal with before, I don't know what I changed because this patching method used to work without issues.

I'm trying to patch a Japanese rm2k game, editing the ldb chipsets and such. I can create an .edb file without issues, but when I convert it back to .ldb, the command line vomits up a bunch of "not well-formed (invalid token)" errors. I've tried the .ini file fix where you add
"[EasyRPG]
Encoding=1252" to RPG_RT.ini, but that creates a whole new even worse problem - all of the Japanese characters get corrupted in the .edb file, and once the new .ldb has been generated, the game has TONS of missing assets to the point where it's completely unplayable
![Player_8MDenQCH3P](https://user-images.githubusercontent.com/42161067/157552592-dc20fdba-6974-41a5-b85e-61808a4fd38e.png)
![cmd_gMasAB3GjA](https://user-images.githubusercontent.com/42161067/157552606-7242e7a0-d5a2-4f61-9e30-c990546fe98c.png)
.

**Comment by Ghabry** [comment]
You must use ``932`` instead of ``1252`` because the game is in Japanese

**Comment by carstene1ns** [comment]
I guess this issue is solved by now.
